name: vy_range_collection
description: A collection library for range.
version: 0.3.0
authors:
- Kwang Yul Seo <kwangyul.seo@gmail.com>
- Giorgio Franceschetti<giorgiofran@gmail.com>
homepage: https://github.com/giorgiofran/vy_range_collection

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

dependencies:
  interval_skip_list: any
  quiver_check: any
  quiver_iterables: any

dev_dependencies:
  test: ^0.12.30